services:

  # ===== Backend =====
  backend_medista:
    build:
      context:  ./backend
      dockerfile: Dockerfile
    container_name: backend_medista
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    ports:
      - "8000:8000"
    depends_on:
      postgres_medista:
        condition: service_healthy
      redis_medista:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ===== POSTGRESQL =====
  postgres_medista:
    image: postgres:16-alpine
    container_name: postgres_medista
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - "5433:5432"
    volumes:
      - medista_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  # ===== REDIS =====
  redis_medista:
    image: redis:7-alpine
    container_name: redis_medista
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - medista_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ===== PROMETHEUS =====
  prometheus_medista:
    image: prom/prometheus:latest
    container_name: prometheus_medista
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - medista_prometheus_data:/prometheus
    
  # ===== GRAFANA =====
  grafana_medista:
    image: grafana/grafana:latest
    container_name: grafana_medista
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - medista_grafana_data:/var/lib/grafana
    depends_on:
      - prometheus_medista
  

volumes:
  medista_postgres_data:
  medista_redis_data:
  medista_prometheus_data:
  medista_grafana_data:
    