-- =============================================================
-- V23__create_envers_revinfo.sql
-- Tabla de revisiones requerida por Hibernate Envers
-- Centraliza los metadatos de cada revisión: número, timestamp y usuario responsable
-- =============================================================

CREATE TABLE revinfo (
    rev        INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    revtstmp   BIGINT,
    user_id    BIGINT       REFERENCES users(id),
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);