spring:
    application:
        name: medista
    
    # ===== DATASOURCE =====
    datasource:
        url: jdbc:postgresql://${DB_HOST:postgres_medista}:${DB_PORT:5432}/${POSTGRES_DB:medista_db}
        username: ${POSTGRES_USER:medista_user}
        password: ${POSTGRES_PASS:medista_user}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            connection-timeout: 30000

    # ===== JPA =====
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                default_schema: public
                org:
                    hibernate:
                        envers:
                            audit_table_suffix: _aud
                            store_data_at_delete: true
                            default_schema: public
                         
        open-in-view: false
    
    # ===== FLYWAY =====
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: false
    
    # ===== REDIS =====
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}
            password: ${REDIS_PASSWORD:}
    
# ===== SERVER =====
server:
    port: 8000
    servlet:
        context-path: /api
    
# ===== ACTUATOR =====
management:
    endpoints:
        web: 
            exposure:
                include: health, info, prometheus
    endpoint:
        health:
            show-details: when-authorized
    
# ===== JWT =====
app:
    jwt:
        secret: ${JWT_SECRET:cambiar-en-produccion-minimo-256-bits-xxxxxxxxxxx}
        expiration-ms: 3600000
        refresh-expiration-ms: 86400000

# ===== JASYPT =====
jasypt:
    encryptor:
        password: ${JASYPT_PASSWORD:cambiar-en-produccion}
        algorithm: PBEWithMACAndAES256
        iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# ===== LOGGING =====
logging:
  level:
    ec.tecazuay.medista: DEBUG
    org.springframework.security: INFO
    org.flywaydb: INFO
